// <auto-generated />
namespace crud_wpf.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addcolomitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolomitem));
        
        string IMigrationMetadata.Id
        {
            get { return "202010160743168_addcolomitem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
